name: test-preg-mini2p
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - ca-certificates
  - certifi
  - openssl
  
  # Core scientific computing
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.1.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - scikit-image=0.22.0
  - statsmodels=0.14.0
  - numba=0.59.0
  - numexpr=2.8.7
  - bottleneck=1.3.7
  - sympy=1.12
  - patsy=0.5.3
  - imbalanced-learn=0.11.0
  
  # Data processing
  - h5py=3.9.0
  - pytables
  - imageio=2.33.1
  - imagecodecs=2023.1.23
  - tifffile=2023.4.12
  - pillow=10.2.0
  - openpyxl=3.0.10
  - xlwings=0.29.1
  
  # Visualization
  - plotly=5.9.0
  - bokeh=3.3.4
  - holoviews=1.18.3
  - hvplot=0.9.2
  - panel=1.3.8
  - datashader=0.16.0
  - altair=5.0.1
  - pydeck=0.8.0
  - streamlit=1.30.0
  - colorcet=3.0.1
  
  # Jupyter ecosystem
  - jupyter=1.0.0
  - jupyterlab=4.0.11
  - notebook=7.0.8
  - ipython=8.18.1
  - ipykernel=6.29.5
  - ipywidgets=7.6.5
  - widgetsnbextension=3.5.2
  - jupyterlab_widgets=3.0.9
  - jupyterlab-variableinspector=3.1.0
  - jupyter_console=6.6.3
  - qtconsole=5.4.2
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nbclient=0.8.0
  
  # IDE and development tools
  - spyder=5.4.3
  - spyder-kernels=2.4.4
  - python-lsp-server=1.7.2
  - pylint=2.16.2
  - autopep8=1.6.0
  - black=23.11.0
  - flake8=6.0.0
  - mypy=1.8.0
  - rope=1.7.0
  - yapf=0.31.0
  
  # Parallel computing and data
  - dask=2023.11.0
  - distributed=2023.11.0
  - xarray=2023.6.0
  - intake=0.6.8
  - cloudpickle=2.2.1
  - fsspec=2023.10.0
  - zarr
  
  # Machine learning
  - gensim=4.3.0
  - nltk=3.8.1
  
  # Astronomy/science
  - astropy=5.3.4
  
  # Arrow/Parquet
  - pyarrow=14.0.2
  
  # Web scraping
  - beautifulsoup4=4.12.2
  - scrapy=2.8.0
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - urllib3=2.0.7
  - lxml=4.9.3
  
  # Cryptography and security
  - cryptography=42.0.2
  - pyjwt=2.4.0
  - bcrypt=3.2.0
  - pynacl=1.5.0
  
  # Cloud/AWS
  - s3fs=2023.10.0
  - aiobotocore=2.7.0
  - botocore=1.31.64
  
  # Qt
  - pyqt=5.15.10
  - pyqtwebengine=5.15.10
  - qtawesome=1.2.2
  - qtpy=2.4.1
  
  # Database
  - sqlalchemy=2.0.25
  - pyodbc=5.0.1
  
  # Utilities
  - tqdm=4.65.0
  - click=8.1.7
  - pyyaml=6.0.1
  - toml=0.10.2
  - jinja2=3.1.3
  - networkx=3.1
  - joblib=1.2.0
  - toolz=0.12.0
  - cytoolz=0.12.2
  - dill=0.3.7
  - filelock=3.13.1
  - packaging=23.1
  - platformdirs=3.10.0
  - setuptools=68.2.2
  - wheel=0.41.2
  - pip=23.3.1
  
  # Documentation
  - sphinx=5.0.2
  - numpydoc=1.5.0
  - docutils=0.18.1
  
  # Testing
  - pytest=7.4.0
  
  # Version control
  - gitpython=3.1.37
  
  # Terminal/shell
  - colorama=0.4.6
  - pygments=2.15.1
  - prompt-toolkit=3.0.43
  
  # Async
  - aiohttp=3.9.3
  
  # Compression
  - zstandard=0.19.0
  - lz4=4.3.2
  - blosc=1.21.3
  
  # Serialization
  - protobuf=3.20.3
  - msgpack-python=1.0.3
  
  # Other
  - markdown=3.4.1
  - tomlkit=0.11.1
  - attrs=23.1.0
  - typing_extensions=4.9.0
  - psutil=5.9.0
  - pywin32=305
  - pywinpty=2.0.10
  - debugpy=1.6.7
  - traitlets=5.7.1
  - decorator=5.1.1
  - six=1.16.0
  - wcwidth=0.2.5
  
  # MKL optimizations
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  
  # pip packages
  - pip:
    - moviepy